#!/bin/bash

cat << EOF > /etc/apt/sources.list.d/mos.list
deb http://172.18.170.22/repos/xenial-mitaka xenial-mitaka main
EOF

cat << EOF > /etc/apt/preferences.d/mos.pref
Package: *
Pin: origin 172.18.170.22
Pin-Priority: 600
EOF

cat << EOF > /etc/apt/apt.conf.d/99allow-unauthenticated
APT::Get::AllowUnauthenticated "true";
EOF

apt-get update

